### ISSUE TITLE
Discuss: Should we upload the latest APK?

### ISSUE THREAD

**Issue by holyhead** [Ethon/Ninja-Coffee#4]
What do you think about that? For me it wouldn't be a big deal to do so.
We could upload the latest afer we did a major modification (e. g. after we completed an issue).

**Comment by Ethon** [comment]
I think we should! There should be a dist - folder containing the latest version.
Building it can be tedious as we all know.

**Comment by holyhead** [comment]
Agreed: I've built and uploaded the latest version in the dist/ folder.
